lacozi_wh/config/routes.rb
LacoziWh::Application.routes.draw do

  resources :categories


  resources :products


  root :to => 'products#home'
  get '/all-products', :to => 'products#index'
  get '/categories', :to => 'categories#index'
  get '/decorative-pillows', :to => 'products#decorative_pillows'
  get '/duvet-sets', :to => 'products#duvet_sets'
  get '/product-details', :to => 'products#details'


end

lacozi_wh/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :products

  validates_uniqueness_of :name
  validates_presence_of :name
  has_many :products
end

lacozi_wh/app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  attr_accessible :category_id, :category, :code, :description, :name, :picture
  belongs_to :category
end

lacozi_wh/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

lacozi_wh/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

lacozi_wh/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json

  def home

  end

  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def decorative_pillows
    @pillows = Product.where(:category_id => 1)
    respond_to do |format|
      format.html
      format.json { render json: @pillows }
    end
  end


  def duvet_sets
    @duvet_sets = Product.where(:category => 'duvet set')
    respond_to do |format|
      format.html
      format.json { render json: @duvet_sets }
    end
  end

  def details
    @details = Product.where(:id => params[:q])
    respond_to do |format|
      format.html
      format.json { render json: @details}
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    @options = Category.all.collect do |c|
        [c.name, c.id]
      end
    # @categories = Category.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])

    @options = Category.all.collect do |c|
        [c.name, c.id]
      end
    # @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

lacozi_wh/app/helpers/application_helper.rb
module ApplicationHelper
end

lacozi_wh/app/helpers/categories_helper.rb
module CategoriesHelper
end

lacozi_wh/app/helpers/products_helper.rb
module ProductsHelper
end

lacozi_wh/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lacozi_wh/app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

lacozi_wh/app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

lacozi_wh/app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

lacozi_wh/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

lacozi_wh/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lacozi</title>
  <meta name='viewport' content='initial-scale=1.0, width=device-width' />
  <meta name="apple-mobile-web-app-capable" content="yes">
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <!-- <link rel="stylesheet" media="all and (orientation:portrait)" href="portrait.css"> -->
  <!-- <link rel="stylesheet" media="all and (orientation:landscape)" href="landscape.css"> -->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id='container'>
    <%= yield %>
  </div>

</body>
</html>

lacozi_wh/app/views/products/_bottom_menu.html.erb
<div id='bottom-menu-div'>
  <ul id='bottom-menu'>
    <a href='/'><li>Home</li></a>
    <a href='/decorative-pillows'><li>Pillows</li></a>
    <a href='/duvet-sets'><li>Duvet Sets</li></a>
    <a href='/sheet-sets'><li>Sheet Sets</li></a>
  </ul>
</div>

lacozi_wh/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>

  <div class="field">
    Category Id:<br />
    <%= f.select :category_id, @options %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lacozi_wh/app/views/products/_main_menu.html.erb
<div id="main-menu">
  <ul id="main-menu-list">
    <a href="/decorative-pillows"><li id='pillows'>PILLOWS</li></a>
    <a href="/duvet-sets"><li id='bedding'>BEDDING</li></a>
  </ul>
</div>

lacozi_wh/app/views/products/_top_logo.html.erb
<a href='/'><h1 id='logo'>LaCozi</h1></a>

lacozi_wh/app/views/products/decorative_pillows.html.erb
<%= render 'top_logo' %>

<h1 class='category'>Decorative Pillows</h1>

<hr id='divider'/>

<div id='product-data'>

</div>

<div class='list'>
  <ul id='dec-pillows' class='item-list grid'>

  </ul>
</div>

<%= render 'bottom_menu' %>

lacozi_wh/app/views/products/details.html.erb
<h1>Product Details</h1>

lacozi_wh/app/views/products/duvet_sets.html.erb
<%= render 'top_logo' %>

<h1 class='category'>Duvet Sets</h1>

<div id='product-data'>

</div>

<div class='list'>
  <ul id='duvet-sets' class='item-list grid'>

  </ul>
</div>

<%= render 'bottom_menu' %>

lacozi_wh/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

lacozi_wh/app/views/products/home.html.erb
  <%= render 'top_logo' %>

  <div id='slider' class='swipe'>
    <div class='swipe-wrap'>
      <div><%= image_tag("Blue-Hotel.jpg") %></div>
      <div><%= image_tag("Gray-Hotel.jpg") %></div>
      <div><%= image_tag("Square-pillows.jpg") %></div>
    </div>
  </div>

  <%= render 'main_menu' %>

lacozi_wh/app/views/products/index.html.erb
<h1>Listing products</h1>

<div id='new_product'>
  <%= link_to 'New Product', new_product_path %>
</div>

<table id='product_table'>
  <tr>
    <th>Name</th>
    <th></th>
    <th>Description</th>
    <th>Code</th>
    <th>Catgr</th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= image_tag product.picture_url(:thumb) if product.picture? %></td>
    <td class='product_description'><%= product.description %></td>
    <td class='product_code'><%= product.code %></td>
    <td class='category_id'><%= product.category_id %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td class='destroy_product'><%= link_to 'X', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

lacozi_wh/app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

lacozi_wh/app/views/products/pillow_index.html.erb
<%= render 'top-logo' %>



<%= render 'main-menu' %>

lacozi_wh/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div id='p-container'>

  <div id='p-image'>
    <%= image_tag(@product.picture_url, :width => 600) if @product.picture.present? %>
  </div>

  <div id='p-name'>
    <h1><%= @product.name %></h1>
  </div>

  <div id='p-description'>
    <%= @product.description %>
  </div>

  <div id='p-code'>
    <b>Product Code:</b>
    <%= @product.code %>
  </div>
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>